# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partsmanagement', '0016_auto_20160214_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='partsmanagement.Part')),
                ('title', models.CharField(default='No title', help_text='The title of a book.', max_length=100, unique=True, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, help_text='The subtitle of a book if there is some', max_length=250, null=True, verbose_name='Subtitle')),
                ('year', models.IntegerField(blank=True, help_text='The publishing year.', null=True, verbose_name='Publishing year')),
                ('isbn10', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN-10')),
                ('isbn13', models.CharField(blank=True, max_length=17, null=True, verbose_name='ISBN-13')),
                ('language', models.CharField(blank=True, help_text='Language media is in. Use ISO-codes here.', max_length=6, null=True, verbose_name='Publishing language')),
                ('comment', models.TextField(blank=True, help_text='A short conclusion.', max_length=200, null=True, verbose_name='Comment')),
            ],
            options={
                'ordering': ['title'],
            },
            bases=('partsmanagement.part',),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, help_text='The first name of author', max_length=100, null=True, verbose_name='First name')),
                ('last_name', models.CharField(help_text='The last name of the publisher.Or, if there is only one name.', max_length=100, verbose_name='Last name')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher', max_length=100, verbose_name='Name')),
                ('place', models.CharField(blank=True, help_text='The place, where the publisher publishes its publications.', max_length=100, null=True, verbose_name='Place')),
            ],
            options={
                'ordering': ['name', 'place'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(help_text='The list of authors of the book.', related_name='_book_author_+', to='bookcollection.Person', verbose_name='Authors'),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(default=None, help_text='The publisher of a book.', on_delete=django.db.models.deletion.CASCADE, to='bookcollection.Publisher', verbose_name='Publisher'),
        ),
        migrations.AddField(
            model_name='book',
            name='translator',
            field=models.ManyToManyField(blank=True, help_text='The list of translators of the book.', related_name='_book_translator_+', to='bookcollection.Person', verbose_name='Translators'),
        ),
    ]
