# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-08-14 16:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import partsmanagement.utils


class Migration(migrations.Migration):

    replaces = [
        ("partsmanagement", "0001_initial"),
        ("partsmanagement", "0002_auto_20141119_1802"),
        ("partsmanagement", "0003_auto_20141121_1814"),
        ("partsmanagement", "0004_auto_20141121_1913"),
        ("partsmanagement", "0005_auto_20141123_1654"),
        ("partsmanagement", "0006_auto_20141205_1350"),
        ("partsmanagement", "0007_auto_20141205_1352"),
        ("partsmanagement", "0008_auto_20150525_1650"),
        ("partsmanagement", "0009_category_description"),
        ("partsmanagement", "0010_storageplace_description"),
        ("partsmanagement", "0011_transaction_state"),
        ("partsmanagement", "0012_transaction_created_date"),
        ("partsmanagement", "0013_auto_20151220_1922"),
        ("partsmanagement", "0014_adjusting_verbose_names_of_model"),
        ("partsmanagement", "0015_adding_price_to_part"),
        ("partsmanagement", "0016_rename_url_to_image_url"),
        ("partsmanagement", "0017_transaction_reverted"),
        ("partsmanagement", "0018_distributor_logo"),
        (
            "partsmanagement",
            "0019_alter_field_desctiption_for_transaction_date",
        ),
        ("partsmanagement", "0020_distributor_url"),
        ("partsmanagement", "0021_adding_logo_and_url_to_manufacturer"),
        ("partsmanagement", "0022_part_change_subfolder"),
        ("partsmanagement", "0023_storageplace_pic"),
        ("partsmanagement", "0024_auto_20160710_1812"),
        ("partsmanagement", "0025_category_pic"),
        ("partsmanagement", "0026_part_data_sheet"),
        ("partsmanagement", "0027_description_and_image_from_storageplace"),
        ("partsmanagement", "0028_storageitem_needs_review"),
        ("partsmanagement", "0029_auto_20170518_2031"),
        ("partsmanagement", "0030_desc_odering_of_transaction"),
        ("partsmanagement", "0031_storageitem_review_reason"),
        ("partsmanagement", "0032_storageplace_owner"),
        ("partsmanagement", "0033_owner_to_storage_item"),
        ("partsmanagement", "0034_auto_20171209_1218"),
    ]

    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partsmanagement.Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Distributor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added by",
                    ),
                ),
            ],
            options={"verbose_name": "Distributor"},
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added by",
                    ),
                ),
            ],
            options={"verbose_name": "Manufacturer"},
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, verbose_name="Name of part"
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Minimal stock",
                    ),
                ),
                (
                    "on_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Parts on stock",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            (
                                "Length",
                                ((b"m", "meters"), (b"cm", "centimeters")),
                            ),
                            (
                                "Volume",
                                (
                                    (b"l", "litres"),
                                    (b"m\xc2\xb3", "cubicmeters"),
                                    (b"ccm", "cubic centimeters"),
                                ),
                            ),
                            (b"---", "Unknown"),
                        ],
                        default=b"---",
                        max_length=3,
                    ),
                ),
                ("creation_time", models.DateTimeField(auto_now_add=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        to="partsmanagement.Category", verbose_name="Category"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Added by",
                    ),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partsmanagement.Distributor",
                        verbose_name="Distributor",
                    ),
                ),
                (
                    "manufacturer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partsmanagement.Manufacturer",
                        verbose_name="Manufacturer",
                    ),
                ),
            ],
            options={"verbose_name": "Part", "verbose_name_plural": "Parts"},
        ),
        migrations.CreateModel(
            name="StoragePlace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
            options={"verbose_name": "Storage Place"},
        ),
        migrations.CreateModel(
            name="StorageType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name for a storage type. Should be unique",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="A short description.",
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "pic",
                    models.ImageField(
                        blank=True,
                        help_text="If you have a typical image of such a storage, this is the place where it belongs to.",
                        null=True,
                        upload_to="uploads/storagetypes/",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Type",
                "verbose_name_plural": "Storage Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=100, verbose_name="Subject"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Amount"
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now_add=True,
                        db_index=True,
                        verbose_name="Transaction Date",
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Comment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="storageplace",
            name="storage_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StorageType",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="storage_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StoragePlace",
                verbose_name="Storage",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Creation time"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Length", ((b"m", "meters"), (b"cm", "centimeters"))),
                    (
                        "Volume",
                        (
                            (b"l", "litres"),
                            (b"m\xc2\xb3", "cubicmeters"),
                            (b"ccm", "cubic centimeters"),
                        ),
                    ),
                    (b"---", "Unknown"),
                ],
                default=b"---",
                max_length=3,
                verbose_name="Messuring unit",
            ),
        ),
        migrations.AlterModelOptions(
            name="distributor",
            options={
                "verbose_name": "Distributor",
                "verbose_name_plural": "Distributors",
            },
        ),
        migrations.AlterModelOptions(
            name="manufacturer",
            options={
                "ordering": ["name"],
                "verbose_name": "Manufacturer",
                "verbose_name_plural": "Manufacturers",
            },
        ),
        migrations.AlterModelOptions(
            name="storageplace",
            options={
                "verbose_name": "Storage Place",
                "verbose_name_plural": "Storage Places",
            },
        ),
        migrations.AddField(
            model_name="storageplace",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StoragePlace",
                verbose_name="Parent storage",
            ),
        ),
        migrations.AlterField(
            model_name="distributor",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Creation time"
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Disabled"),
        ),
        migrations.AddField(
            model_name="storageplace",
            name="disabled",
            field=models.BooleanField(default=False, verbose_name="Disabled"),
        ),
        migrations.AlterField(
            model_name="part",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Length", ((b"m", "meters"), (b"cm", "centimeters"))),
                    (
                        "Volume",
                        (
                            (b"l", "litres"),
                            (b"m\xc2\xb3", "cubicmeters"),
                            (b"ccm", "cubic centimeters"),
                        ),
                    ),
                    ("n/A", "Unknown"),
                ],
                default=b"---",
                max_length=3,
                verbose_name="Messuring unit",
            ),
        ),
        migrations.CreateModel(
            name="StorageItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "on_stock",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="Parts inside storage",
                    ),
                ),
                (
                    "disabled",
                    models.BooleanField(
                        default=False, verbose_name="Disabled"
                    ),
                ),
                (
                    "part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partsmanagement.Part",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="partsmanagement.StoragePlace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Storage Item",
                "verbose_name_plural": "Storage Items",
            },
        ),
        migrations.AlterUniqueTogether(
            name="storageitem", unique_together=set([("part", "storage")])
        ),
        migrations.RemoveField(model_name="part", name="on_stock"),
        migrations.RemoveField(model_name="part", name="storage_place"),
        migrations.AddField(
            model_name="part",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="sku",
            field=models.CharField(
                blank=True,
                max_length=60,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="storage_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StorageItem",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Name of part"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="category", unique_together=set([("name", "parent")])
        ),
        migrations.AlterField(
            model_name="part",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Length", ((b"m", "meters"), (b"cm", "centimeters"))),
                    (
                        "Volume",
                        (
                            (b"l", "litres"),
                            (b"m\xc2\xb3", "cubicmeters"),
                            (b"ccm", "cubic centimeters"),
                        ),
                    ),
                    ("Piece", ((b"pc", "piece"),)),
                    ("n/A", "Unknown"),
                ],
                default=b"---",
                max_length=3,
                verbose_name="Messuring unit",
            ),
        ),
        migrations.AddField(
            model_name="storageplace",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"paid", "Paid"),
                    (b"open", "Open"),
                    (b"res", "Reserverd"),
                ],
                default=b"---",
                max_length=6,
                verbose_name="State",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="created_date",
            field=models.TimeField(
                auto_now_add=True,
                db_index=True,
                default=datetime.datetime(
                    2015, 11, 28, 12, 41, 3, 896981, tzinfo=utc
                ),
                verbose_name="Creation timestamp",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="pic",
            field=models.ImageField(
                blank=True, null=True, upload_to=b"uploads/"
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="url",
            field=models.CharField(
                blank=True, max_length=255, null=True, unique=True
            ),
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="distributor",
            options={
                "ordering": ["name"],
                "verbose_name": "Distributor",
                "verbose_name_plural": "Distributors",
            },
        ),
        migrations.AlterModelOptions(
            name="part",
            options={
                "ordering": ["name"],
                "verbose_name": "Part",
                "verbose_name_plural": "Parts",
            },
        ),
        migrations.AlterModelOptions(
            name="storageitem",
            options={
                "ordering": ["storage", "part"],
                "verbose_name": "Storage Item",
                "verbose_name_plural": "Storage Items",
            },
        ),
        migrations.AlterModelOptions(
            name="storageplace",
            options={
                "ordering": ["name"],
                "verbose_name": "Storage Place",
                "verbose_name_plural": "Storage Places",
            },
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["date"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A short summarize of this category.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="Name of the category.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If having a subcateogry, the parent.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.Category",
            ),
        ),
        migrations.AlterField(
            model_name="distributor",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created the distributor.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added by",
            ),
        ),
        migrations.AlterField(
            model_name="distributor",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp the distributor was created at.",
                verbose_name="Creation time",
            ),
        ),
        migrations.AlterField(
            model_name="distributor",
            name="name",
            field=models.CharField(
                help_text="Name of the distributor", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user the manufacturer was created by.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added by",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp the manufacturer was created at.",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="name",
            field=models.CharField(
                help_text="Name of the manufacturer.", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="categories",
            field=models.ManyToManyField(
                help_text="A list of categories the part is in.",
                to="partsmanagement.Category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user the part was created by.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added by",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Timestamp the part was created on.",
                verbose_name="Creation time",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A long text description of the part",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the part is active or not.",
                verbose_name="Disabled",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                help_text="The usual distributor of the part.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.Distributor",
                verbose_name="Distributor",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                help_text="The manufacturer of the part.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.Manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="min_stock",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Set a minimum that should be stored.",
                max_digits=10,
                null=True,
                verbose_name="Minimal stock",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="name",
            field=models.CharField(
                help_text="Name of the part.",
                max_length=255,
                verbose_name="Name of part",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="pic",
            field=models.ImageField(
                blank=True,
                help_text="The actual image.",
                null=True,
                upload_to=b"uploads/",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="sku",
            field=models.CharField(
                blank=True,
                help_text="A installation unique idendifier for the part.",
                max_length=60,
                null=True,
                unique=True,
                verbose_name="SKU",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Length", ((b"m", "meters"), (b"cm", "centimeters"))),
                    (
                        "Volume",
                        (
                            (b"l", "litres"),
                            (b"m\xc2\xb3", "cubicmeters"),
                            (b"ccm", "cubic centimeters"),
                        ),
                    ),
                    ("Piece", ((b"pc", "piece"),)),
                    ("n/A", "Unknown"),
                ],
                default=b"---",
                help_text="The unit quantities are in.",
                max_length=3,
                verbose_name="Messuring unit",
            ),
        ),
        migrations.RenameField(
            model_name="part", old_name="url", new_name="image_url"
        ),
        migrations.AlterField(
            model_name="part",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="The URL of the original image.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether the storage item is active.",
                verbose_name="Disabled",
            ),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="on_stock",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="The amount currently stored.",
                max_digits=10,
                null=True,
                verbose_name="Parts inside storage",
            ),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="part",
            field=models.ForeignKey(
                help_text="The part stored at this spot.",
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.Part",
            ),
        ),
        migrations.AlterField(
            model_name="storageitem",
            name="storage",
            field=models.ForeignKey(
                help_text="The storage the part is stored in.",
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StoragePlace",
            ),
        ),
        migrations.AlterField(
            model_name="storageplace",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A short description.",
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="storageplace",
            name="disabled",
            field=models.BooleanField(
                default=False,
                help_text="Whether a storage is active.",
                verbose_name="Disabled",
            ),
        ),
        migrations.AlterField(
            model_name="storageplace",
            name="name",
            field=models.CharField(
                help_text="A name for the storage place.E.g. coordinates inside a book shelve.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="storageplace",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The storage the current storage is part of.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StoragePlace",
                verbose_name="Parent storage",
            ),
        ),
        migrations.AlterField(
            model_name="storageplace",
            name="storage_type",
            field=models.ForeignKey(
                help_text="Of which type is the storage place.",
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StorageType",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=4,
                help_text="The quantity transferred.",
                max_digits=10,
                verbose_name="Amount",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.TextField(
                blank=True,
                help_text="A short conclusion.",
                max_length=200,
                null=True,
                verbose_name="Comment",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                help_text="The user which created the transaction.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Created by",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="created_date",
            field=models.TimeField(
                auto_now_add=True,
                db_index=True,
                help_text="The timestamp transaction has been entered.",
                verbose_name="Creation timestamp",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime.now,
                help_text="The data the transaction take part.",
                verbose_name="Transaction Date",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    (b"paid", "Paid"),
                    (b"open", "Open"),
                    (b"res", "Reserverd"),
                ],
                default=b"---",
                help_text="The status a transaction is in.",
                max_length=6,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="storage_item",
            field=models.ForeignKey(
                blank=True,
                help_text="The part-storage relation the transaction was applied on.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StorageItem",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="subject",
            field=models.CharField(
                help_text="A short conclusion of the transaction.",
                max_length=100,
                verbose_name="Subject",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="The cost/price for the part",
                max_digits=6,
                null=True,
                verbose_name="Cost of the part",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="reverted",
            field=models.BooleanField(
                default=False,
                help_text="To control whether transaction has been already reverted and cannot be reverted again.",
                verbose_name="Reverted",
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="The logo of the company.",
                null=True,
                upload_to="uploads/logos/",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime.now,
                help_text="The date the transaction took  part.",
                verbose_name="Transaction Date",
            ),
        ),
        migrations.AddField(
            model_name="distributor",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="The URL to homepage of distributor.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="The logo of the company.",
                null=True,
                upload_to="uploads/logos/",
            ),
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="The URL to homepage of manufacturer.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="pic",
            field=models.ImageField(
                blank=True,
                help_text="The actual image.",
                null=True,
                upload_to=b"part",
            ),
        ),
        migrations.AddField(
            model_name="storageplace",
            name="pic",
            field=models.ImageField(
                blank=True,
                help_text="So does look the place in real.",
                null=True,
                upload_to="uploads/storageplaces/",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="pic",
            field=models.ImageField(
                blank=True,
                help_text="The actual image.",
                null=True,
                upload_to="part",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="unit",
            field=models.CharField(
                choices=[
                    ("Length", (("m", "meters"), ("cm", "centimeters"))),
                    (
                        "Volume",
                        (
                            ("l", "litres"),
                            ("m³", "cubicmeters"),
                            ("ccm", "cubic centimeters"),
                        ),
                    ),
                    ("Piece", (("pc", "piece"),)),
                    ("n/A", "Unknown"),
                ],
                default="---",
                help_text="The unit quantities are in.",
                max_length=3,
                verbose_name="Messuring unit",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("paid", "Paid"),
                    ("open", "Open"),
                    ("res", "Reserverd"),
                ],
                default="---",
                help_text="The status a transaction is in.",
                max_length=6,
                verbose_name="State",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="pic",
            field=models.ImageField(
                blank=True,
                help_text="Some picutre for category.",
                null=True,
                upload_to="uploads/categories/",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="data_sheet",
            field=models.FileField(
                blank=True,
                help_text="A document containing important addition information",
                null=True,
                upload_to="datasheets",
                validators=[partsmanagement.utils.validate_file_extension],
                verbose_name="Data sheet",
            ),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="needs_review",
            field=models.BooleanField(
                default=False,
                help_text="Whether this storage item might be wrong",
                verbose_name="Needs review",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="storage_item",
            field=models.ForeignKey(
                help_text="The part-storage relation the transaction was applied on.",
                on_delete=django.db.models.deletion.CASCADE,
                to="partsmanagement.StorageItem",
            ),
        ),
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
        migrations.AddField(
            model_name="storageitem",
            name="review_reason",
            field=models.TextField(
                blank=True,
                help_text="Put reason, why this item should be reviewed here in.",
                null=True,
                verbose_name="Reason for Review",
            ),
        ),
        migrations.AddField(
            model_name="storageplace",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user who is responsible for the storage.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owned by",
            ),
        ),
        migrations.AddField(
            model_name="storageitem",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="The user owning items of this storageitem.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Owned by",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storageitem",
            unique_together=set([("part", "storage", "owner")]),
        ),
        migrations.AlterField(
            model_name="distributor",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created the distributor.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added by",
            ),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The user the manufacturer was created by.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Added by",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="distributor",
            field=models.ForeignKey(
                blank=True,
                help_text="The usual distributor of the part.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partsmanagement.Distributor",
                verbose_name="Distributor",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                help_text="The manufacturer of the part.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partsmanagement.Manufacturer",
                verbose_name="Manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="storageplace",
            name="storage_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Of which type is the storage place.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="partsmanagement.StorageType",
            ),
        ),
    ]
