# Generated by Django 2.1.1 on 2018-09-09 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0005_auto_20180909_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, help_text='The date the transaction took part.', verbose_name='Transaction Date'),
        ),
    ]
