# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 15:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0013_auto_20151220_1922'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='distributor',
            options={'ordering': ['name'], 'verbose_name': 'Distributor', 'verbose_name_plural': 'Distributors'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['name'], 'verbose_name': 'Part', 'verbose_name_plural': 'Parts'},
        ),
        migrations.AlterModelOptions(
            name='storageitem',
            options={'ordering': ['storage', 'part'], 'verbose_name': 'Storage Item', 'verbose_name_plural': 'Storage Items'},
        ),
        migrations.AlterModelOptions(
            name='storageplace',
            options={'ordering': ['name'], 'verbose_name': 'Storage Place', 'verbose_name_plural': 'Storage Places'},
        ),
        migrations.AlterModelOptions(
            name='storagetype',
            options={'ordering': ['name'], 'verbose_name': 'Storage Type', 'verbose_name_plural': 'Storage Types'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['date'], 'verbose_name': 'Transaction', 'verbose_name_plural': 'Transactions'},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='A chance to summarize usage of category.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='Name of the category.', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='If having a subcateogry, the parent.', null=True, on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.Category'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='created_by',
            field=models.ForeignKey(help_text='User who created the distributor.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp the distributor was created at.', verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='name',
            field=models.CharField(help_text='Name of the distributor', max_length=50),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(help_text='The user the manufacturer was created by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp the manufacturer was created at'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(help_text='Name of the manufacturer.', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='categories',
            field=models.ManyToManyField(help_text='A list of categories the part is in.', to='partsmanagement.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='part',
            name='created_by',
            field=models.ForeignKey(help_text='The user the part was created by.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='part',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp the part was created on.', verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.TextField(blank=True, help_text='A long text description of the part', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='part',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Whether the part is active or not.', verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='part',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='The usual distributor of the part.', null=True, on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.Distributor', verbose_name='Distributor'),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='The manufacturer of the part.', null=True, on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='part',
            name='min_stock',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Set a minimum that should be stored.', max_digits=10, null=True, verbose_name='Minimal stock'),
        ),
        migrations.AlterField(
            model_name='part',
            name='name',
            field=models.CharField(help_text='Name of the part.', max_length=255, verbose_name='Name of part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='pic',
            field=models.ImageField(blank=True, help_text='The actual image.', null=True, upload_to=b'uploads/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='sku',
            field=models.CharField(default=0, help_text='A installation unique idendifier for the part.', max_length=60, unique=True, verbose_name='SKU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='part',
            name='unit',
            field=models.CharField(choices=[('Length', ((b'm', 'meters'), (b'cm', 'centimeters'))), ('Volume', ((b'l', 'litres'), (b'm\xc2\xb3', 'cubicmeters'), (b'ccm', 'cubic centimeters'))), ('Piece', ((b'pc', 'piece'),)), ('n/A', 'Unknown')], default=b'---', help_text='The unit quantities are in.', max_length=3, verbose_name='Messuring unit'),
        ),
        migrations.AlterField(
            model_name='part',
            name='url',
            field=models.CharField(blank=True, help_text='The URL of the original image.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Whether the storage item is active.', verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='on_stock',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='The amount currently stored.', max_digits=10, null=True, verbose_name='Parts inside storage'),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='part',
            field=models.ForeignKey(help_text='The part stored at this spot.', on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.Part'),
        ),
        migrations.AlterField(
            model_name='storageitem',
            name='storage',
            field=models.ForeignKey(help_text='The storage the part is stored in.', on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.StoragePlace'),
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='description',
            field=models.TextField(blank=True, help_text='A short description.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='disabled',
            field=models.BooleanField(default=False, help_text='Whether a storage is active.', verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='name',
            field=models.CharField(help_text='A name for the storage place.E.g. coordinates inside a book shelve.', max_length=50),
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The storage the current storage is part of.', null=True, on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.StoragePlace', verbose_name='Parent storage'),
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='storage_type',
            field=models.ForeignKey(help_text='Of which type is the storage place.', on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.StorageType'),
        ),
        migrations.AlterField(
            model_name='storagetype',
            name='name',
            field=models.CharField(help_text='The name for a storage type. Should be unique', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='The quantity transferred.', max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='comment',
            field=models.TextField(blank=True, help_text='A short conclusion.', max_length=200, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_by',
            field=models.ForeignKey(help_text='The user which created the transaction.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_date',
            field=models.TimeField(auto_now_add=True, db_index=True, help_text='The timestamp transaction has been entered.', verbose_name='Creation timestamp'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, help_text='The data the transaction take part.', verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(blank=True, choices=[(b'paid', 'Paid'), (b'open', 'Open'), (b'res', 'Reserverd')], default=b'---', help_text='The status a transaction is in.', max_length=6, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='storage_item',
            field=models.ForeignKey(blank=True, help_text='The part-storage relation the transaction was applied on.', null=True, on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.StorageItem'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subject',
            field=models.CharField(help_text='A short conclusion of the transaction.', max_length=100, verbose_name='Subject'),
        ),
    ]
