# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0014_adjusting_verbose_names_of_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The cost/price for the part', max_digits=6, null=True, verbose_name='Cost of the part'),
        ),
    ]
