# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0015_adding_price_to_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='url',
            new_name='image_url',
        ),
    ]
