# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 21:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0016_rename_url_to_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reverted',
            field=models.BooleanField(default=False, help_text='To control whether transaction has been already reverted and cannot be reverted again.', verbose_name='Reverted'),
        ),
    ]
