# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0018_distributor_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now, help_text='The date the transaction took  part.', verbose_name='Transaction Date'),
        ),
    ]
