# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0019_alter_field_desctiption_for_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='url',
            field=models.URLField(blank=True, help_text='The URL to homepage of distributor', null=True),
        ),
    ]
