# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-26 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0020_distributor_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo of the company.', null=True, upload_to=b'uploads/logos/'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='url',
            field=models.URLField(blank=True, help_text='The URL to homepage of manufacturer.', null=True),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='url',
            field=models.URLField(blank=True, help_text='The URL to homepage of distributor.', null=True),
        ),
    ]
