# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0022_part_change_subfolder'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageplace',
            name='pic',
            field=models.ImageField(blank=True, help_text='So does look the place in real.', null=True, upload_to=b'uploads/storageplaces/'),
        ),
    ]
