# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-10 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0023_storageplace_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo of the company.', null=True, upload_to='uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='logo',
            field=models.ImageField(blank=True, help_text='The logo of the company.', null=True, upload_to='uploads/logos/'),
        ),
        migrations.AlterField(
            model_name='part',
            name='pic',
            field=models.ImageField(blank=True, help_text='The actual image.', null=True, upload_to='part'),
        ),
        migrations.AlterField(
            model_name='part',
            name='unit',
            field=models.CharField(choices=[('Length', (('m', 'meters'), ('cm', 'centimeters'))), ('Volume', (('l', 'litres'), ('m³', 'cubicmeters'), ('ccm', 'cubic centimeters'))), ('Piece', (('pc', 'piece'),)), ('n/A', 'Unknown')], default='---', help_text='The unit quantities are in.', max_length=3, verbose_name='Messuring unit'),
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='pic',
            field=models.ImageField(blank=True, help_text='So does look the place in real.', null=True, upload_to='uploads/storageplaces/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='state',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('open', 'Open'), ('res', 'Reserverd')], default='---', help_text='The status a transaction is in.', max_length=6, verbose_name='State'),
        ),
    ]
