# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-30 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0024_auto_20160710_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pic',
            field=models.ImageField(blank=True, help_text='Some picutre for category.', null=True, upload_to='uploads/categories/'),
        ),
    ]
