# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import partsmanagement.models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0025_category_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='data_sheet',
            field=models.FileField(blank=True, help_text='A document containing important addition information', null=True, upload_to='datasheets', validators=[partsmanagement.models.validate_file_extension], verbose_name='Data sheet'),
        ),
    ]
