# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0026_part_data_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagetype',
            name='description',
            field=models.TextField(blank=True, help_text='A short description.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='storagetype',
            name='pic',
            field=models.ImageField(blank=True, help_text='If you have a typical image of such a storage, this is the place where it belongs to.', null=True, upload_to='uploads/storagetypes/'),
        ),
    ]
