# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0027_description_and_image_from_storageplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Whether this storage item might be wrong', verbose_name='Needs review'),
        ),
    ]
