# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-18 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0028_storageitem_needs_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='storage_item',
            field=models.ForeignKey(help_text='The part-storage relation the transaction was applied on.', on_delete=django.db.models.deletion.CASCADE, to='partsmanagement.StorageItem'),
        ),
    ]
