# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-03 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0030_desc_odering_of_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='review_reason',
            field=models.TextField(blank=True, help_text='Put reason, why this item should be reviewed here in.', null=True, verbose_name='Reason for Review'),
        ),
    ]
