# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-14 16:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('partsmanagement', '0032_storageplace_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageitem',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user owning items of this storageitem.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owned by'),
        ),
        migrations.AlterUniqueTogether(
            name='storageitem',
            unique_together=set([('part', 'storage', 'owner')]),
        ),
    ]
