# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-09 12:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partsmanagement', '0033_owner_to_storage_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the distributor.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user the manufacturer was created by.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Added by'),
        ),
        migrations.AlterField(
            model_name='part',
            name='distributor',
            field=models.ForeignKey(blank=True, help_text='The usual distributor of the part.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partsmanagement.Distributor', verbose_name='Distributor'),
        ),
        migrations.AlterField(
            model_name='part',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='The manufacturer of the part.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='partsmanagement.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='The user who is responsible for the storage.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owned by'),
        ),
        migrations.AlterField(
            model_name='storageplace',
            name='storage_type',
            field=models.ForeignKey(blank=True, help_text='Of which type is the storage place.', null=True, on_delete=django.db.models.deletion.PROTECT, to='partsmanagement.StorageType'),
        ),
    ]
